//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientsDish
    {
        public int ID { get; set; }
        public int Dish { get; set; }
        public int Ingredient { get; set; }
    
        public virtual Dish Dish1 { get; set; }
        public virtual Ingredients Ingredients { get; set; }
    }
}
